from typing import Optional, List
from uuid import UUID
from src.domain.models import Payment, PaymentStatus

class PaymentRepository:
    def add(self, payment: Payment) -> Payment: ...
    def get(self, payment_id: UUID) -> Optional[Payment]: ...
    def list(self, status: Optional[PaymentStatus] = None) -> List[Payment]: ...
    def update_status(self, payment_id: UUID, status: PaymentStatus) -> Payment: ...
